//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserData()
        {
            this.ClickDatas = new HashSet<ClickData>();
        }
    
        public int UserID { get; set; }
        public System.Guid UniqueStringID { get; set; }
        public bool InUse { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string WinDeviceID { get; set; }
        public string WinProductID { get; set; }
        public string AndroidID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClickData> ClickDatas { get; set; }
    }
}
